-- Public portfolio case study for Sentinel (documentation only — no live tool link).

INSERT INTO public.projects (
  title,
  title_jp,
  description,
  technologies,
  github,
  demo,
  featured,
  color,
  sort_order,
  slug,
  status,
  tier,
  tagline,
  status_note,
  long_description,
  accent_color,
  show_demo_link,
  metrics
) VALUES (
  'SENTINEL',
  'Sentinel',
  'A private security auditing platform I built to explore web security, vulnerability assessment, HTTP security, networking and secure software development.',
  ARRAY['React', 'TypeScript', 'FastAPI', 'Python', 'PostgreSQL', 'Docker', 'HTTP', 'TLS'],
  NULL,
  NULL,
  true,
  'from-rose-700 to-zinc-800',
  6,
  'sentinel',
  'in_development',
  'featured',
  'Personal Security Assessment Platform',
  'Private admin tool — not publicly accessible',
  E'## Why I built Sentinel\n\nI wanted a private security command centre inside my own admin ecosystem — not a public SaaS scanner. Building Sentinel is how I learn web security by implementing real HTTP, TLS, header, cookie, and CORS analysis with honest limitations.\n\n## Security concepts explored\n\n- Trust boundaries and allowlisted targets\n- Passive vs active testing\n- Security headers and cookie hardening\n- TLS certificate observation\n- CORS configuration pitfalls\n- Explainable internal scoring (not CVSS)\n\n## Architecture\n\n- Admin UI at `/admin/sentinel` (private)\n- FastAPI scan service on localhost\n- Modular Python checks under `sentinel/scanner`\n- Postgres/SQLite persistence for targets, scans, and findings\n\n## Key features\n\n- Target allowlist\n- Passive non-destructive checks\n- Structured findings with evidence and remediation\n- Sentinel Security Score with documented arithmetic\n- Private reports (including PDF)\n\n## What I learned\n\nSecurity tools must refuse unsafe scope, explain uncertainty, and never pretend a header scan is a penetration test.\n\n## Future improvements\n\n- Richer TLS configuration review\n- Authenticated-page checks with explicit lab fixtures\n- Deeper historical comparison and export formats',
  'from-rose-700 to-zinc-800',
  false,
  '[{"label":"Scope","value":"Private"},{"label":"Focus","value":"Passive web security"},{"label":"Stack","value":"React + FastAPI"}]'::jsonb
)
ON CONFLICT (title) DO UPDATE SET
  slug = EXCLUDED.slug,
  status = EXCLUDED.status,
  tier = EXCLUDED.tier,
  tagline = EXCLUDED.tagline,
  status_note = EXCLUDED.status_note,
  description = EXCLUDED.description,
  long_description = EXCLUDED.long_description,
  technologies = EXCLUDED.technologies,
  demo = EXCLUDED.demo,
  featured = EXCLUDED.featured,
  color = EXCLUDED.color,
  sort_order = EXCLUDED.sort_order,
  accent_color = EXCLUDED.accent_color,
  show_demo_link = EXCLUDED.show_demo_link,
  metrics = EXCLUDED.metrics,
  updated_at = now();
